import time
import requests
from datetime import datetime, timezone

urls = [
    "https://anti-india-detection.onrender.com",
    "https://mca-econsult-prototype.onrender.com"
]

print("Ping script started...")

# 6 pings, ~10s apart -> ~1 minute total 
with requests.Session() as sess:
    for i in range(6):
        now = datetime.now(timezone.utc).isoformat()
        print(f"\nTick: {now}  (iteration {i+1}/6)")

        for url in urls:
            try:
                # Use GET; change to HEAD if server supports it and you want lighter checks
                r = sess.get(url, timeout=10)
                print(f"[{url}] status={r.status_code} reason={r.reason} time={r.elapsed.total_seconds():.2f}s")
            except requests.exceptions.RequestException as e:
                print(f"[{url}] request error: {e!s}")

        # don't sleep after the last iteration
        if i < 5:
            time.sleep(10)
